### PR TITLE
Automated tests

### PR DESCRIPTION
**Pull request by joannekoch**
Download dir changes, timing changes.

### CODE REVIEW

**Comment by ethanandrews** [comment]
Hey @joannekoch . This PR threw an error in the automated tests, looks like in the upload CSV test:

https://github.com/WHOIGit/ooicgsn-roundabout/actions/runs/11560851463/job/32178593375?pr=675

**Review by ethanandrews — CHANGES_REQUESTED** [review]
Check error in csv uploads

**Comment by joannekoch** [comment]
Yes, you weren't in last week's meeting and I mentioned that my tests will fail until Mario fixes the issue with the Deployment download. It's throwing an Attribute error.

I submitted my PR in advance because there were substantial changes that needed to be made for my tests to run.

Joanne

From: Ethan Andrews ***@***.***>
Sent: Monday, November 4, 2024 10:15 AM
To: WHOIGit/ooicgsn-roundabout ***@***.***>
Cc: Joanne Koch ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [WHOIGit/ooicgsn-roundabout] Automated tests (PR #675)

This email originated outside of WHOI. Please use caution if clicking on links or opening attachments.

@ethanandrews requested changes on this pull request.

Check error in csv uploads

-

**Comment by ethanandrews** [comment]
Gotcha, thanks!

From: Joanne Koch ***@***.***>
Date: Monday, November 4, 2024 at 10:18 AM
To: WHOIGit/ooicgsn-roundabout ***@***.***>
Cc: Ethan Andrews ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [WHOIGit/ooicgsn-roundabout] Automated tests (PR #675)
This email originated outside of WHOI. Please use caution if clicking on links or opening attachments.

**Pull request merged**
